import pytest
from app.models.chat import ConversationStateEnum
from app.models.chat import ClarifyRequest

@pytest.mark.asyncio
async def test_t1_t2(pipeline, sample_schema, sample_adapter, conversation):
    # T1
    msg1 = await pipeline.process_query(
        "give me the product categories that we have",
        conversation, sample_schema, sample_adapter
    )
    conversation.messages.append(msg1)
    
    msg2 = await pipeline.process_query(
        "category wise revenue generated so far",
        conversation, sample_schema, sample_adapter
    )
    assert msg2.sql is not None
    assert "revenue" in msg2.sql.lower() or "sum" in msg2.sql.lower()
    conversation.messages.append(msg2)

    # T2
    msg3 = await pipeline.process_query(
        "i am asking revenue generated per category",
        conversation, sample_schema, sample_adapter
    )
    assert msg3.sql is not None
    assert "revenue" in msg3.sql.lower() or "sum" in msg3.sql.lower()

@pytest.mark.asyncio
async def test_t3(pipeline, sample_schema, sample_adapter, conversation):
    msg1 = await pipeline.process_query(
        "what is the highest priced product",
        conversation, sample_schema, sample_adapter
    )
    conversation.messages.append(msg1)
    
    msg2 = await pipeline.process_query(
        "its sales",
        conversation, sample_schema, sample_adapter
    )
    assert msg2.clarification is not None

@pytest.mark.asyncio
async def test_t4(pipeline, sample_schema, sample_adapter, conversation):
    msg1 = await pipeline.process_query(
        "who is our recent customer",
        conversation, sample_schema, sample_adapter
    )
    assert msg1.clarification is not None
    
    clarif_req = ClarifyRequest(field_name=msg1.clarification.field_name, custom_input="last ordered")
    msg2 = await pipeline.process_clarification(clarif_req, conversation, sample_schema, sample_adapter)
    assert msg2.sql is not None

@pytest.mark.asyncio
async def test_t5(pipeline, sample_schema, sample_adapter, conversation):
    msg1 = await pipeline.process_query(
        "show me customer 1",
        conversation, sample_schema, sample_adapter
    )
    conversation.messages.append(msg1)
    
    msg2 = await pipeline.process_query(
        "total revenue generated by her",
        conversation, sample_schema, sample_adapter
    )
    assert msg2.sql is not None
    assert "WHERE" in msg2.sql.upper() and ("c.id" in msg2.sql.lower() or "customer_id" in msg2.sql.lower())

@pytest.mark.asyncio
async def test_t6_t7_t8(pipeline, sample_schema, sample_adapter, conversation):
    msg1 = await pipeline.process_query(
        "give me top 10 customers as per number of placed orderes",
        conversation, sample_schema, sample_adapter
    )
    conversation.messages.append(msg1)
    assert "COUNT" in msg1.sql.upper()
    
    msg2 = await pipeline.process_query(
        "revenue we get from them",
        conversation, sample_schema, sample_adapter
    )
    conversation.messages.append(msg2)
    assert "IN (" in msg2.sql.upper()
    
    msg3 = await pipeline.process_query(
        "i am asking total",
        conversation, sample_schema, sample_adapter
    )
    assert "SUM" in msg3.sql.upper()


@pytest.mark.asyncio
async def test_t9_no_metric_leakage(pipeline, sample_schema, sample_adapter, conversation):
    """T9: 'most popular products' -> 'give me the most highest priced product' -> ranking by price, no units_sold leakage."""
    msg1 = await pipeline.process_query(
        "most popular products",
        conversation, sample_schema, sample_adapter
    )
    # Should be ambiguous (popular is unclear)
    assert msg1.clarification is not None
    conversation.messages.append(msg1)

    msg2 = await pipeline.process_query(
        "give me the most highest priced product",
        conversation, sample_schema, sample_adapter
    )
    assert msg2.sql is not None
    assert "price" in msg2.sql.lower()
    assert "units_sold" not in msg2.sql.lower()
    assert "total_units_sold" not in msg2.sql.lower()


@pytest.mark.asyncio
async def test_t10_multi_hop(pipeline, sample_schema, sample_adapter, conversation):
    """T10: multi-hop: expensive product -> what category -> category revenue."""
    msg1 = await pipeline.process_query(
        "show the most expensive product",
        conversation, sample_schema, sample_adapter
    )
    assert msg1.sql is not None
    assert "price" in msg1.sql.lower()
    conversation.messages.append(msg1)

    msg2 = await pipeline.process_query(
        "what category is it in?",
        conversation, sample_schema, sample_adapter
    )
    assert msg2.sql is not None
    conversation.messages.append(msg2)

    msg3 = await pipeline.process_query(
        "how much revenue did that category generate?",
        conversation, sample_schema, sample_adapter
    )
    assert msg3.sql is not None
    assert "revenue" in msg3.sql.lower() or "sum" in msg3.sql.lower()


@pytest.mark.asyncio
async def test_t11_inheritance_and_reset(pipeline, sample_schema, sample_adapter, conversation):
    """T11: 'customers from India' -> 'how many are there?' inherits India, then 'show expensive products' resets."""
    msg1 = await pipeline.process_query(
        "customers from India",
        conversation, sample_schema, sample_adapter
    )
    assert msg1.sql is not None
    assert "India" in msg1.sql
    conversation.messages.append(msg1)

    msg2 = await pipeline.process_query(
        "how many are there?",
        conversation, sample_schema, sample_adapter
    )
    assert msg2.sql is not None
    assert "COUNT" in msg2.sql.upper()
    assert "India" in msg2.sql
    conversation.messages.append(msg2)

    msg3 = await pipeline.process_query(
        "show expensive products",
        conversation, sample_schema, sample_adapter
    )
    assert msg3.classification.value == "NEW_QUERY"
    # Must not carry India filter
    assert "India" not in (msg3.sql or "")


@pytest.mark.asyncio
async def test_t12_refinement_chain(pipeline, sample_schema, sample_adapter, conversation):
    """T12: 'top 10 customers' -> 'actually make that top 5' -> 'by order count, not spending' -> each edits the same plan."""
    msg1 = await pipeline.process_query(
        "top 10 customers",
        conversation, sample_schema, sample_adapter
    )
    assert msg1.sql is not None
    assert "LIMIT 10" in msg1.sql.upper()
    conversation.messages.append(msg1)

    msg2 = await pipeline.process_query(
        "actually make that top 5",
        conversation, sample_schema, sample_adapter
    )
    assert msg2.sql is not None
    assert "LIMIT 5" in msg2.sql.upper()
    conversation.messages.append(msg2)

    msg3 = await pipeline.process_query(
        "by order count, not spending",
        conversation, sample_schema, sample_adapter
    )
    assert msg3.sql is not None
    assert "COUNT" in msg3.sql.upper()


@pytest.mark.asyncio
async def test_t13_context_switch(pipeline, sample_schema, sample_adapter, conversation):
    """T13: 'show top customers' -> 'forget that, which products are expensive?' -> fresh context + threshold clarification."""
    msg1 = await pipeline.process_query(
        "show top customers",
        conversation, sample_schema, sample_adapter
    )
    assert msg1.sql is not None
    conversation.messages.append(msg1)

    msg2 = await pipeline.process_query(
        "forget that, which products are expensive?",
        conversation, sample_schema, sample_adapter
    )
    # Should be a clarification about "expensive"
    assert msg2.clarification is not None
    assert "price" in msg2.clarification.question.lower() or "expensive" in msg2.clarification.question.lower()
